spring:
  application:
    name: api-gateway

server:
  port: 1101

zuul:
  routes:
#  single-instance
    api-a:
      path: /api-a/**
      url: http://localhost:20001/
#  multi-instance
    api-b:
      path: /api-b/**
      serviceId: api-b

api-b:
  ribbon:
    listOfServers: http://localhost:20001/, http://localhost:20002/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1002/eureka/
